/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package operator.vue.graph;

/**
 *
 * @author Thoma
 */
public class EncodePort extends javax.swing.JPanel {

    /**
     * Creates new form EncodePort
     */
    public EncodePort() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLCodePort = new javax.swing.JLabel();
        JTFCodePort = new javax.swing.JTextField();
        JLVille = new javax.swing.JLabel();
        JTFVille = new javax.swing.JTextField();
        JLPays = new javax.swing.JLabel();
        JTFPays = new javax.swing.JTextField();
        JBOk = new javax.swing.JButton();
        JBClear = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(4, 2));

        JLCodePort.setText("CodePort");
        add(JLCodePort);

        JTFCodePort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFCodePortActionPerformed(evt);
            }
        });
        add(JTFCodePort);

        JLVille.setText("Ville");
        add(JLVille);
        add(JTFVille);

        JLPays.setText("Pays");
        add(JLPays);
        add(JTFPays);

        JBOk.setText("OK");
        JBOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBOkActionPerformed(evt);
            }
        });
        add(JBOk);

        JBClear.setText("CLEAR");
        add(JBClear);
    }// </editor-fold>//GEN-END:initComponents

    private void JTFCodePortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFCodePortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFCodePortActionPerformed

    private void JBOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBOkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBOkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBClear;
    private javax.swing.JButton JBOk;
    private javax.swing.JLabel JLCodePort;
    private javax.swing.JLabel JLPays;
    private javax.swing.JLabel JLVille;
    private javax.swing.JTextField JTFCodePort;
    private javax.swing.JTextField JTFPays;
    private javax.swing.JTextField JTFVille;
    // End of variables declaration//GEN-END:variables
}
